## Contents
- loop문 제어
    - break
    - continue
- 파일 읽고 쓰기
    - 기본1
    - 기본2
    - pandas
    - numpy

## Loop 문 제어
- 중단
    - break
- skip
    - continue

In [21]:
# break 예시
for i in range(5):
    if i == 3:
        break
    print(i)

0
1
2


In [22]:
# continue 예시
for i in range(5):
    if i == 3:
        continue
    print(i)

0
1
2
4


## 파일 읽고 쓰기
- 종류
    - 파일 객체 버전 
    - pandas 버전
    - numpy 버전
    
- 파일 객체
    1. 파일 객체 만들기
        ```python
            # 파일을 열어 f라는 파일 객체를 만든다.
            f = open(파일 경로, mode=...)
        ```
        - 파일 경로 
            - 절대경로
                - 서울특별시 관악구 신림동 서울대학교 ...
                - 예) `/Users/haekyu/Downloads/jinseohyun/0812`
            - 상대경로
                - 내 위치에서 오른쪽으로 한 칸
                - .: 현재 위치
                - ..: 상위 경로
                - 하위 경로는 이름을 그냥 쓰면 됨
        - mode: 
            - 'r' : read
            - 'w' : write
            - 'a' : append
    2. 파일 읽기 (mode='r' 인 경우)
        - 한방에 읽어오기
            - `readlines()` 함수 사용
            - 예)
                ```python
                f = open('sample.txt', mode='r')
                lst = f.readlines()
                f.close()
                ```
        - 한 라인씩 읽어오기
            - `readline()` 함수 사용
            - EOF (End of file) 에 닿을 때까지 무한 루프로 읽음
            - 예)
                ```python
                f = open('sample.txt', mode='r')
                while True:
                    line = f.readline()
                    print(line)
                    if line == '':
                        break
                f.close()
                ```
    3. 파일 쓰기 (mode='w' 혹은 mode='a' 인 경우)
        - `write(원하는 스트링)` 함수 사용
        - Newline(엔터) 를 넣고싶으면 '\n' 을 추가
        - 예)
            ```python
            f = open('sample.txt', mode='w')
            f.write('A\n')
            f.write('B\n')
            f.write('C\n')
            f.write('D\n')
            f.write('E')
            f.close()
            ```
    4. 파일 닫기
        - `close()` 함수 사용
        - 반드시 닫아줘야함!!!!! 안그러면 다른 프로세스가 해당 파일을 열 때 뭔가 꼬여버림.

- pandas 를 통해 읽기/쓰기
    - Column 별로 저장된 데이터를 읽고 쓸 때 pandas를 사용한다.
    - `*.csv` 나 `*.tsv` 파일들을 읽을 때 주로 사용
        - `*.csv`: comma separated values
        - `*.tsv`: tab separated values
    - pandas library를 import 해와야 함.
        ```python
        # pandas library를 가져와서 pd 라고 부른다
        import pandas as pd
        ```
    - 파일 읽기: [pandas.read_csv](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_csv.html) 함수 사용
        - 텍스트 파일을 읽어서 DataFrame 형식으로 저장한다.
            - DataFrame 이라는 data type이 따로 있음
            - DataFrame 은 데이터를 행/렬로 구분한 2D table이라고 생각하면 됨 ([참고](http://pinkwink.kr/735))
            - DataFrame 은 dictionray 비슷하게 구현되어있음.
                - key: column 의 이름
                - val: 해당 column의 data 들
        - 대표적인 parameters
            - filepath_or_buffer: path of file to read
            - sep: separator, a string used to separate values
            - names: list of column names to use
                - ex) ['State', 'No. of Presidents']
                - 만약 names가 주어지지 않으면, names는 자동으로 텍스트파일의 가장 첫 번째 row가 된다.
            - dtype: Type name or dict of column -> type, default None
        - 예) [./data/profile.csv](./data/profile.csv) 읽기
            ```python
            import pandas as pd
            df = pd.read_csv('./data/profile.csv', sep=',')
            print(df)
            ```
            출력 결과
            ```
                 name  age address
            0    Kate   10     ABC
            1  Robert   22     AAA
            2     Tom   15     VVV
            3   Chloe   21     VVV
            ```
        - column names 얻기
            - `dataframe.columns` 를 통해 column 이름들을 얻을 수 있음.
            - 예)
                ```python
                names = df.columns
                print(names)

                name_lst = list(names)
                print(name_lst)
                ```
                출력 결과
                ```
                Index(['name', 'age', 'address'], dtype='object')
                ['name', 'age', 'address']
                ```
        - cf) [pandas.read_excel](https://pandas.pydata.org/pandas-docs/version/0.20/generated/pandas.read_excel.html) 함수: Excel 파일을 읽어 DataFrame으로 저장하기
    - 파일 쓰기: [pandas.DataFrame.to_csv](http://pandas.pydata.org/pandas-docs/version/0.23/generated/pandas.DataFrame.to_csv.html) 사용
        - DataFrame 을 파일로 저장
        - 대표적인 parameters
            - path_or_buf: 저장할 파일 경로
            - sep: separator
        - 예)
            ```python
            df.to_csv('./data/profile.tsv', sep='\t')
            ```
            ['./data/profile.tsv]('./data/profile.tsv) 를 열어보면 아래와 같다. 값들이 tab으로 구분되어있음
            ```
            	name	age	address
            0	Kate	10	ABC
            1	Robert	22	AAA
            2	Tom	15	VVV
            3	Chloe	21	VVV

            ```
- numpy 를 통해 읽기/쓰기
    - 숫자 자체를 읽어올 때 numpy 사용
        - ex) matrix를 읽어올 때
    - numpy library를 import 해와야 함
        ```python
        # numpy library를 가져와서 np 라고 부른다
        import numpy as np
        ```
    - 파일 읽기: [numpy.loadtxt](https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.loadtxt.html) 함수 사용
        - text 파일을 읽어와서 array로 리턴한다.
        - 대표적인 parameters
            - fname: name/path of a text file
            - dtype: data type
            - delimiter: a string used to separate values
        - return data read from the text file
        - 예)
            ```python
            import numpy as np
            mat = np.loadtxt('./sample-mat.txt', dtype=int, delimiter=' ')
            print(mat)
            ```
            출력 결과
            ```
            [[-1  2  1]
             [ 5  2 -1]
             [ 3  2  1]]
            ```
    - 파일 쓰기: [numpy.savetxt](https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.savetxt.html) 함수 사용
        - array_like (numpy array, list, tuple, ...) data를 text file로 저장한다.
        - 대표적인 parameters
            - fname: name/path of a text file
            - X: array_like data to be saved to the text file
            - fmt: format of values. ex) '%d', '%.2lf', ...
            - delimiter: a string used to separate values
        - does not return anything (return None)
        - 예)
            ```python
            # Import numpy and say it as np
            import numpy as np

            # Read sample-mat.txt
            mat = np.loadtxt('./data/sample-mat.txt', dtype=int, delimiter=' ')
            
            # Make transpose of mat
            trans_mat = mat.T

            # Save trans_mat
            np.savetxt('./data/sample-transpose-mat.txt', trans_mat, fmt='%d', delimiter=' ')
            ```
            ['./data/sample-transpose-mat.txt'](./data/sample-transpose-mat.txt) 를 열어보면 아래와 같다.
            ```
            -1 5 3
            2 2 2
            1 -1 1
            ```

In [16]:
## Pandas 예시 -- read_csv()

import pandas as pd

path = './data/profile.csv'
df = pd.read_csv(path)
print(df)

     name  age address
0    Kate   10     ABC
1  Robert   22     AAA
2     Tom   15     VVV
3   Chloe   21     VVV


In [17]:
# Pandas 예시 -- column 가져오기
print(df['name'])

0      Kate
1    Robert
2       Tom
3     Chloe
Name: name, dtype: object


In [18]:
# Pandas 예시 -- 값 가져오기
print(df['name'][1])

Robert


In [19]:
# Pandas 예시 -- 값 수정하기

print('before df:')
print(df)

df['name'][1] = 'ROBERT'

print('\nafter df:')
print(df)

before df:
     name  age address
0    Kate   10     ABC
1  Robert   22     AAA
2     Tom   15     VVV
3   Chloe   21     VVV

after df:
     name  age address
0    Kate   10     ABC
1  ROBERT   22     AAA
2     Tom   15     VVV
3   Chloe   21     VVV


/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  


In [11]:
# Pandas 예시 -- pandas.DataFrame 만들기 (from dictionary)

df2 = pd.DataFrame(
    {
     'name': ['Kate', 'Robert', 'Tom', 'Chole'],
     'age': [10, 22, 15, 21]
    }
)

print(df2)

     name  age
0    Kate   10
1  Robert   22
2     Tom   15
3   Chole   21


In [20]:
# Pandas 예시 -- pandas.DataFrame.to_csv()
df2.to_csv('./data/df2.csv')

## Pandas의 Data Frame
- DataFrame 이란 panel data를 표현하는 데이터 타입이다.
    - Panel data: spreadsheets에서 잘 표현되는 table 형식의 데이터
    - cf) Data Frame은 Pandas라는 라이브러리를 사용해야 하는데, Pandas가 Pan(el) Da(ta) 의 줄임말이라고 한다.
    - `import pandas as pd`
- Data frame 만들기
    - Empty data frame 만들기
        - 예)
            ```python
            import pandas as pd
            my_empty_df = pd.DataFrame()
            ```
    - 기존 data frame에 컬럼 추가하기
        - `데이터프레임[컬럼명] = 컬럼 데이터`
        - 예)
            ```python
            import pandas as pd

            # Empty data frame
            profile_df = pd.DataFrame()

            # Add name column
            profile_df['name'] = ['chul', 'young', 'soo']

            # Add age column
            profile_df['age'] = [1, 2, 3]

            # Add addr column
            profile_df['addr'] = ['Busan', 'Incheon', 'Seoul']

            print(profile_df)
            ```
            출력 결과
            ```
                name  age     addr
            0   chul    1    Busan
            1  young    2  Incheon
            2    soo    3    Seoul
            ```
    - Dictionary를 통해 만들기
        - key는 컬럼명이고, value는 해당 컬럼의 벡터이다.
        - 예)
            ```python
            d = {'name': ['chul', 'young', 'soo'],
                 'age': [1, 2, 3],
                 'addr': ['Busan', 'Incheon', 'Seoul']}

            # Dictionary를 DataFrame으로 형변환
            profile_df = pd.DataFrame(d)

            print(profile_df)
            ```
            출력 결과
            ```
                name  age     addr
            0   chul    1    Busan
            1  young    2  Incheon
            2    soo    3    Seoul
            ```

## Numpy
- Numpy는 Numeric object을 만들어 활용하는 패키지
- 필요한 기능이 있을 때마다 구글을 검색하시면 좋아요!
- Numpy array 만들기
    - `np.zeros(shape)`: shape 모양의 0으로 채워진 array를 생성
    - `np.ones(shape)`: shape 모양의 1로 채워진 array를 생성
    - `np.random.rand(shape)`: shape 모양의 0~1 사이의 랜덤숫자로 채워진 array를 생성
    - `np.array(어떤 list)`: list를 numpy array로 형변환
    - 예)
        ```python
        >>> np.zeros(3)
        array([ 0.,  0.,  0.])

        >>> np.zeros((2, 3))
        array([[ 0.,  0.,  0.],
               [ 0.,  0.,  0.]])
        ```
- array 계산 (numeric 계산)
    - 사칙 연산 가능
        - 예)
            ```python
            # v1과 v2 정의
            >>> v1 = np.array([1, 2, 3])
            >>> v2 = np.array([-3, -2, -1])

            # vector와 scalar의 계산
            >>> v1 + 1
            array([2, 3, 4])
            >>> v1 * 0.5
            array([ 0.5,  1. ,  1.5])

            # vector와 vector의 계산
            >>> v1 + v2
            array([-2,  0,  2])
            ```
    - dot product (내적)
        - `v1.dot(v2)`
        - 예)
            ```python
            # v1과 v2 정의
            >>> v1 = np.array([1, 2, 3])
            >>> v2 = np.array([-3, -2, -1])

            # v1과 v2의 내적
            >>> v1.dot(v2)
            -10
            ```
    - array들의 곱하기
        - `np.matmul(arr1, arr2)`
        - 두 array의 곱은 행렬곱이 될 수도 있고 벡터의 내적이 될 수도 있음.

In [25]:
# numpy 예시 -- np.zeros()
import numpy as np

vec1 = np.zeros(4)
mat1 = np.zeros((2, 3))

print(vec1)
print()
print(mat1)

[0. 0. 0. 0.]

[[0. 0. 0.]
 [0. 0. 0.]]


In [27]:
# numpy 예시 -- np.ones()
m1 = np.ones((2, 3))
m2 = np.ones((2, 3))

print(m1)
print()
print(m2)

[[1. 1. 1.]
 [1. 1. 1.]]

[[1. 1. 1.]
 [1. 1. 1.]]


In [29]:
# numpy 예시 -- +, - 연산
m3 = m1 + m2
m4 = m1 - m2

print(m3)
print()
print(m4)

[[2. 2. 2.]
 [2. 2. 2.]]

[[0. 0. 0.]
 [0. 0. 0.]]


In [32]:
# numpy 예시 -- transpose
m4 = m2.T # (3, 2)

print('before transpose')
print(m2)
print('\nafter transpose')
print(m4)

before transpose
[[1. 1. 1.]
 [1. 1. 1.]]

after transpose
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [42]:
# numpy 예시 -- matrix multiplication
m5 = np.matmul(m2, m4) # (2, 3) * (3, 2) ==> (2, 2)
m6 = m2.dot(m4) # (2, 3) * (3, 2) ==> (2, 2)

print(m5)
print()
print(m6)

[[3. 3.]
 [3. 3.]]

[[3. 3.]
 [3. 3.]]


In [46]:
# numpy 예시 -- elementwise 연산
y = 10 * np.random.rand(3, 2) 

print('y')
print(y)

print('\ny + 1')
print(y + 1)

print('\ny ** 2')
print(y ** 2)

y
[[3.41670923 1.0690695 ]
 [9.75275339 9.80080804]
 [4.72243395 3.66382891]]

y + 1
[[ 4.41670923  2.0690695 ]
 [10.75275339 10.80080804]
 [ 5.72243395  4.66382891]]

y ** 2
[[11.67390193  1.1429096 ]
 [95.11619876 96.05583825]
 [22.30138238 13.42364228]]


In [52]:
# numpy 예시 -- indexing

print('list 버전 matrix indexing: mat[row][col]')
mat_lst = [[1, 2, 3], [4, 5, 6]]
val = mat_lst[1][2]
print(mat_lst)
print('mat_lst[1][2]:', val)

print()
print('np.array 버전 matrix indexing: mat[row, col]')
mat_arr = np.array(mat_lst)
val = mat_arr[1, 2]
print(mat_arr)
print('mat_lst[1, 2]:', val)

list 버전 matrix indexing: mat[row][col]
[[1, 2, 3], [4, 5, 6]]
mat_lst[1][2]: 6

np.array 버전 matrix indexing: mat[row, col]
[[1 2 3]
 [4 5 6]]
mat_lst[1, 2]: 6


## Git
+ Why Git?
    - 코드의 version 관리
        - 매 수정마다 screenshot(commit) 을 남김
    - 협업 용이
        - 여러 사람들의 수정이 동시에 반영이 가능
        - 다른 사람들이 어떻게 수정했는지 볼 수 있음
+ 다운로드
    - Git bash
        - Windows 용: https://git-scm.com/download/win 에서 다운로드
        - 설치 후 Git bash 가 잘 실행되는지 체크
        - bash 를 사용하실 경우 아래에 있는 linux 커맨드를 일부 알아야합니다
    - Git GUI
        - https://git-scm.com/download/gui/windows
+ 용어
    - Local
        - 내 컴퓨터
        - client 느낌. Git server와 통신(?) 하는 내 컴퓨터
    - Repository
        - server 느낌. Git server의 코드 저장소
    - Clone
        - Git server의 repository 를 local로 복사해오는 행위
    - Commit
        - Git 에서의 screenshot
    - Push
        - Local 에서 Git repository로 정보를 전달하는 행위
    - Pull 
        - Git repository의 정보를 Local로 가져오는 행위 
+ 간단한 사용방법 (bash 사용방법)
    - local과 repository를 연동시키기
        - `git clone 레포지토리주소`
            - 레포지토리 주소는 각 레포지토리 홈화면에서 Clone or download 버튼을 누르면 나옴.
    - 파일 추가
        - add
            - `git add 추가할 파일 이름`
            - git add . 하면 모든 수정된 파일이 add 됨.
        - commit
            - `git commit -m "commit 메세지"`
        - push
            - `git push`
    - 파일 받아오기
        - `git pull`

## Linux command
- 혹시나 git bash 를 사용하시게 되면 linux command를 일부 알아야합니다!
- `clear`
    - 화면 정리.
- `ls`
    - list의 줄임말. 현재 위치의 file list를 보여줌.
    - 옵션
        - `ls -a`
            - list all. 숨김파일까지 보여줌
        - `ls -l`
            - 만들어진 날짜 / 파일 크기 등 기타 정보도 보여줌. 
        - `ls -t`
            - 시간순 배열
        - `ls -alt` 등으로 여러 옵션을 한꺼번에 줄 수 있다.
- `cd`
    - change directory. 내가 원하는 디렉토리로 이동
    - `cd 내가_이동하고_싶은_디렉토리_경로`
        - ex) `cd ~/Desktop` 하면 바탕화면으로 이동
    - cf) ~ 은 홈 화면을 의미. 윈도우에서는 `C:/Users/내 이름/` 이었던 것으로 기억하는데 잘은 모르겠습니다.
- `mkdir`
    - make directory. 디렉토리 생성
    - mkdir 원하는_디렉토리_이름
- `cp`
    - copy. 파일 복사
    - `cp from_path to_path`
        - ex) `cp love.txt ../love2.txt` 하면 현재 디렉토리의 love.txt를 상위 폴더의 love2.txt로 복사
    - 옵션
        - `cp -r from_path to_path`
            - 디렉토리 복사
            - 디렉토리를 복사하고싶으면 반드시 -r 옵션을 줘야 함.
- `mv`
    - move. 파일/디렉토리 이동 
    - move from to
- `rm`
    - remove
    - rm 파일이름
    - 옵션
        - `rm -r 디렉토리`
            - 디렉토리 제거
        - `rm -i 파일`
            - 파일 삭제하기 전에 정말 삭제할 거냐고 yes or no 물어봄.
            - 우리는 alias를 통해 rm 을 하면 항상 rm -i가 실행되게끔 만들어 놓음.

## Shell
- Linux 느낌의 까만 화면! (그러한 프로세스)
- git bash 에서 bash가 shell중 하나
- bash 설정 등등
    - `~/.bash_profile` 에서 설정
    - `source ~/.bash_profile` 로 설정한 것들 컴퓨터에 적용
    - 구글에 bash_profile 환경 설정 검색하면 예쁜 설정 많음

In [61]:
def tf_idf(input_path):

    '''
    Read documents
    '''
    
    f = open(input_path, 'r')
    documents = f.readlines()
    f.close()
    
    
    '''
    Parse documents (remove "\n" and "." in all document)
    '''
    
    for d, document in enumerate(documents):
        parsed_document = document.replace('\n', '').replace('.', '')
        documents[d] = parsed_document

        
    '''
    Get tf score
    '''

    # Initialize tf_dict
    #  - key: (d, w)
    #  - val: tf(d, w)
    tf_dict = {}
    
    # Get tf scores
    for d, document in enumerate(documents):
        
        # Get all words in document
        words = document.split(' ')
        
        # For all words, get frequency of words
        # word_freq_dict[w] = w가 document 안에서 나타난 횟수
        word_freq_dict = {}
        for w in words:
            if w not in word_freq_dict:
                word_freq_dict[w] = 0
            word_freq_dict[w] = word_freq_dict[w] + 1
        
        # Get max_freq_d
        max_freq_d = max(list(word_freq_dict.values()))
        
        # For all words, get tf(d, w) score, using word_freq_dict and max_freq_d
        # tf(d, w) = 0.5 + (0.5 * w가 d안에서 나타난 횟수) / (max_freq_d)
        for w in words:
            tf_dict[(d, w)] = 0.5 + (0.5 * word_freq_dict[w]) / max_freq_d
      

    '''
    Get idf score
    '''
    
    # Initialize document_count_dict
    #  - key: w
    #  - val: w가 포함된 document의 개수
    document_count_dict = {}
    
    for d, document in enumerate(documents):
        
        # Get all words in document
        words = document.split(' ')
        
        # Get document_count_dict
        for w in words:
            if w not in document_count_dict:
                document_count_dict[w] = 0
            document_count_dict[w] = document_count_dict[w] + 1
    
    # Initialize idf_dict
    #  - key: w
    #  - val: idf(w)
    # idf(w) = log (N / w가 포함된 document의 개수)
    idf_dict = {}
    
    N = len(documents)
    for w in document_count_dict.keys():
        idf_dict[w] = np.log(N / document_count_dict[w])
        
        
    '''
    Get tf_idf score
    '''
    
    # Initialize tf_idf_dict
    #  - key: (d, w)
    #  - val: tf_idf(d, w) 
    # tf_idf(d, w) = tf(d, w) * idf(w)
    tf_idf_dict = {} 
    
    for d, w in tf_dict.keys():
        tf_idf_dict[(d, w)] = tf_dict[(d, w)] * idf_dict[w]
    
    return tf_idf_dict

tf_idf_dict = tf_idf('./data/documents.txt')

In [62]:
tf_idf_dict

{(0, 'I'): 0.719122666963206,
 (0, 'will'): 1.9237120180961527,
 (0, 'never'): 2.0604531856916184,
 (0, 'be'): 1.9237120180961527,
 (0, 'this'): 2.227810849177276,
 (0, 'young'): 2.7476712345972345,
 (0, 'again'): 2.7476712345972345,
 (0, 'Ever'): 2.7476712345972345,
 (0, 'Oh'): 2.7476712345972345,
 (0, 'damn'): 3.267531620017194,
 (0, 'just'): 2.227810849177276,
 (0, 'got'): 2.0604531856916184,
 (0, 'older'): 2.7476712345972345,
 (1, 'We'): 3.258096538021482,
 (1, 'need'): 3.258096538021482,
 (1, 'to'): 0.9894129967031178,
 (1, 'rent'): 4.356708826689592,
 (1, 'a'): 1.5234954826333755,
 (1, 'room'): 4.356708826689592,
 (1, 'for'): 2.159484249353372,
 (1, 'our'): 4.356708826689592,
 (1, 'party'): 4.356708826689592,
 (2, 'I'): 0.719122666963206,
 (2, 'want'): 2.747270914255491,
 (2, 'more'): 3.6635616461296463,
 (2, 'detailed'): 3.6635616461296463,
 (2, 'information'): 3.6635616461296463,
 (3, 'I'): 0.719122666963206,
 (3, 'love'): 3.6635616461296463,
 (3, 'eating'): 3.6635616461296463,

In [68]:
def is_palindrome(word):
    alphabet_sequence = list(filter(str.isalpha, word.lower()))
    n = len(alphabet_sequence)
    
    for i, alphabet in enumerate(alphabet_sequence):

        # Check only half of the sequence
        if i == int(n / 2):
            break
        
        # Check if i-th word is matched with the last i-th word
        i_th_word = alphabet
        last_i_th_word = alphabet_sequence[n - i - 1]
        if i_th_word != last_i_th_word:
            break
        
    
is_palindrome('no lemon, no meLon')

['n', 'o', 'l', 'e', 'm', 'o', 'n', 'n', 'o', 'm', 'e', 'l', 'o', 'n']


In [63]:
def get_1st_alpha(word):
    return word[0]

word = "apple"
alpha = get_1st_alpha(word)
print(alpha)

a
